package cli

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/shuaiZend/mage-mediagc/internal/action"
	"github.com/shuaiZend/mage-mediagc/internal/media"
)

func newCacheCmd(a *app) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "cache",
		Short: "Manage Magento's derived thumbnail cache",
		Long: `Magento stores every resized variant under catalog/product/cache/<md5(params)>/.

Those files are derived data: they are regenerated on first request and no
database row refers to them by name. Emptying the tree is the safest large
win available, typically 15-30% of media size.`,
	}
	cmd.AddCommand(newCacheStatsCmd(a), newCacheCleanCmd(a))
	return cmd
}

func newCacheStatsCmd(a *app) *cobra.Command {
	return &cobra.Command{
		Use:   "stats",
		Short: "Report the size and file count of the derived cache",
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := a.cfg.Validate(false); err != nil {
				return err
			}
			if err := action.EnsureMediaPathExists(a.cfg.Magento.MediaPath); err != nil {
				return err
			}
			files, bytes, err := action.CacheStats(cmd.Context(), a.cfg.Magento.MediaPath)
			if err != nil {
				return err
			}
			fmt.Fprintf(a.stdout, "cache dir : %s\n", a.cfg.Magento.MediaPath+"/"+media.CacheDirName)
			fmt.Fprintf(a.stdout, "files     : %d\n", files)
			fmt.Fprintf(a.stdout, "size      : %s\n", media.HumanBytes(bytes))
			if files == 0 {
				fmt.Fprintf(a.stdout, "\nnothing to clean\n")
			}
			return nil
		},
	}
}

func newCacheCleanCmd(a *app) *cobra.Command {
	var apply bool
	cmd := &cobra.Command{
		Use:   "clean",
		Short: "Empty the derived thumbnail cache (regenerated automatically)",
		Long: `Empties catalog/product/cache and recreates the directory with the same
ownership, so the web server can keep writing to it.

This operation is safe and reversible in the only sense that matters: the
content is regenerated by Magento on demand. Expect a temporary slowdown on
the first requests after cleaning, and consider warming the cache afterwards:

  php bin/magento catalog:images:resize

Without --apply only the planned work is reported.`,
		Example: `  mage-mediagc cache clean            # measure only
  mage-mediagc cache clean --apply    # do it`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := a.cfg.Validate(false); err != nil {
				return err
			}
			res, err := action.CleanCache(cmd.Context(), a.cfg.Magento.MediaPath, !apply, nil)
			if err != nil {
				return err
			}

			verb := "would remove"
			if apply {
				verb = "removed"
			}
			fmt.Fprintf(a.stdout, "%s: %s\n", a.cfg.Magento.MediaPath+"/"+media.CacheDirName, verb)
			fmt.Fprintf(a.stdout, "  files : %d\n", res.RemovedFiles)
			fmt.Fprintf(a.stdout, "  size  : %s\n", media.HumanBytes(res.RemovedBytes))
			if apply {
				fmt.Fprintf(a.stdout, "  cache directory recreated: %v\n", res.Recreated)
				fmt.Fprintf(a.stdout, "\nMagento will regenerate cached images on demand.\n")
			} else if res.RemovedFiles > 0 {
				fmt.Fprintf(a.stdout, "\nrun again with --apply to perform the cleanup\n")
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&apply, "apply", false, "perform the deletion (default is a dry run)")
	return cmd
}
